version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - streaming_api
      - metadata_api

  streaming_api:
    build:
      context: ./streaming-api
    ports:
      - "8001:443"
    volumes:
      - ./static:/app/static
      - ./certs:/app/certs

  metadata_api:
    build:
      context: ./metadata-api/build
    ports:
      - "8002:443"
    volumes:
      - ./certs:/app/certs

  db_postgres:
    image: postgres:15
    restart: on-failure
    volumes:
      - ./pg_db:/var/lib/postgresql@15/data/
    env_file:
      - src/.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_postgres
    env_file:
      - src/.env
    ports:
      - "5555:5555"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./certs:/etc/ssl/certs
    depends_on:
      - streaming-api

volumes:
  dbdata6:
  db_postgres:
    driver: local