version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:3000"
    depends_on:
      - streaming_api
      - metadata_api

  streaming_api:
    build:
      context: ./streaming-api
    ports:
      - "8001:8001"
    volumes:
      - ./static:/app/static
      # - ./certs:/app/certs

  metadata_api:
    build:
      context: ./metadata-api
    ports:
      - "8002:8002"
    env_file:
      - ./metadata-api/internal/config/.env
    depends_on:
      - db_postgres
    # volumes:
    #   - ./certs:/app/certs

  db_postgres:
    image: postgres:15
    restart: on-failure
    volumes:
      - ./pg_db:/var/lib/postgresql@15/data/
    env_file:
      - ./metadata-api/internal/config/.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_postgres
    env_file:
      - ./metadata-api/internal/config/.env
    ports:
      - "5555:80"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    #   - "8443:443"
    # volumes:
    #   - ./certs:/etc/ssl/certs
    depends_on:
      - streaming_api
      - metadata_api
      - frontend
      
volumes:
  dbdata6:
  db_postgres:
    driver: local